export const CANVAS_DEFAULT_IMAGE = "https://lh3.googleusercontent.com/aida-public/AB6AXuDAXBpKX_c9xdMy5DAP6jiuUloPmpM1e7-sZzkm0wyHm-F0w6a02ShZppTVqZXt_EfrGcRTgKJUtqG16JJHbRYq3zr1KcGaw3UvLUCfaCDJxLNUvnew7mRC8cZhS1hbEh8GTz_kStpdV4ArW8pPmg2hM2CO_20Y_F6OQ_qNpgX02oVqPTonTi3QMHbQOEIkUUkii0vAnLBmKYpibEVLpK8ubx5ZAhQFuHMNcJA3U5YWRO0Io6M_Cx-tF-dGeysqrRtVxAzuwEroMcE";

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:3001/api";
